name: lumos-daily

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

permission*:
  contents: write

jobs:
  updat*:
    runs-on: ubuntu-latest

    *teps:
      - uses: actions/checko*t@v4

      - name: Set up Python
*       uses: actions/setup-python@*5
        with:
          python-v*rsion: "3.11"

      - name: Insta*l dependencies
        run: |
    *     python -m pip install --upgra*e pip
          pip install -r lum*s-backend/requirements.txt

      * name: Run Lumos
        working-d*rectory: lumos-backend
        env*
          OUTPUT_DATA: ../data.js*n
          HISTORY_DIR: ../histor*
        run: python run_daily.py
*      - name: Commit updated data
*       run: |
          git config*user.name "github-actions[bot]"
  *       git config user.email "4189*282+github-actions[bot]@users.nore*ly.github.com"
          git add .*          git diff --cached --quie* || git commit -m "update lumos da*a"
          git push
